### PR TITLE
Refactor elemental editor to extend FormField and setup a template

### PR DESCRIPTION
**Pull request by ScopeyNZ**

### CODE REVIEW

**Comment by robbieaverill** [comment]
Can you please fix the tests and make this PR on the origin repo?

**Comment by ScopeyNZ** [comment]
Oh you want me to just directly update this branch, and then PR the whole thing against the origin repo as WIP?

**Comment by robbieaverill** [comment]
It's all open source, I don't see why we shouldn't make PRs directly against origin. We should be mindful of leaving the branches in states where they're still semi-usable, but in this case there's probably not a huge amount we can do.

Perhaps we could create a new PHP class to use instead of replacing the old one

**Comment by ScopeyNZ** [comment]
I agree it's all open source - but part of the reason of having a team repo is so we can work on WIP features (still open source) and PR them into origin when they're ready I thought? Regardless we're going to be major version bumping again so having master as unstable isn't a big problem, we should just update the branch alias at the same time so nobody with existing version requirements has to deal with breakage.

**Comment by ScopeyNZ** [comment]
Also I feel like creating a new PHP class instead of just editing to replace is a little much - if we've already resigned to changing the API... Although it would be a short lived period with two classes, it's still technical debt of two classes (one that's not used)

**Comment by robbieaverill** [comment]
>we should just update the branch alias at the same time so nobody with existing version requirements has to deal with breakage.

I've already done that - you're right, we treat master as unstable

Up to you, but I see no reason not to PR into origin, that way people can see what we're doing

**Comment by ScopeyNZ** [comment]
I was thinking about this more. PRing each change into origin means it's easier to review. Worrying about breaking some poor soul who's using `dev-master` as a constraint is pretty dumb - they're dumb in the first place for setting a constraint like that.

I'll just merge this (with fastforward) into my main branch and PR to origin. 👍

**Pull request closed without merging**
